# Generated by Django 3.2 on 2021-09-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(blank=True, max_length=64, null=True)),
                ('body', models.CharField(max_length=512)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('website_slug', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
