# Generated by Django 3.2 on 2021-09-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(max_length=512),
        ),
    ]
