# Generated by Django 3.2 on 2021-09-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0002_alter_project_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
