# Generated by Django 3.2 on 2021-06-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationitem',
            options={'ordering': ('-startDate',)},
        ),
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ('-startDate',)},
        ),
    ]
