# Generated by Django 3.2 on 2021-06-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0003_alter_workitem_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
