# Generated by Django 3.2 on 2021-06-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0004_alter_workitem_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
